# Python for begginer

Nunber

In [2]:
x = 3
print(type(x))

<class 'int'>


In [3]:
print(x)
print(x + 1)
print(x * 2)
print(x ** 2)

3
4
6
9


In [4]:
x += 1
print(x)

4


In [5]:
x *= 2
print(x)

8


In [6]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


In [7]:
# caculate logic

In [8]:
t = True
f = False
print(type(t))
print(t and f)
print(not t)
print(t != f)

<class 'bool'>
False
False
True


In [9]:
hello = 'hello'
world = 'world'
print(hello)
print(len(hello))

hello
5


In [10]:
hw = hello + ' ' + world
print(hw)

hello world


In [11]:
hw12 = '%s %s %d' %(hello, world, 12)
print(hw12)

hello world 12


In [12]:
s = 'hello'
print(s.capitalize())
print(s.upper())
print(s.replace('l', '(ell)'))
print('   world'.strip()) # delete white space at begin and end

Hello
HELLO
he(ell)(ell)o
world


# Containers
### contaner such as: lists, dictionaries

List

In [13]:
xs = [3, 1, 2]
print(xs, xs[2])
print(xs[-1])
xs[2] = 'foo'
print(xs)

[3, 1, 2] 2
2
[3, 1, 'foo']


In [14]:
xs.append('bar')
print(xs)

[3, 1, 'foo', 'bar']


In [15]:
x = xs.pop()
print(x, xs)

bar [3, 1, 'foo']


In [16]:
# slicing

In [19]:
nums = list(range(5))
print(nums)

[0, 1, 2, 3, 4]


In [20]:
print(nums[2:4])

[2, 3]


In [21]:
print(nums[2:])

[2, 3, 4]


In [22]:
print(nums[:])

[0, 1, 2, 3, 4]


In [23]:
print(nums[:-1])

[0, 1, 2, 3]


In [24]:
nums[2:4] = [8, 9]
print(nums)

[0, 1, 8, 9, 4]


In [25]:
# Loops

In [27]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print("{}: {}".format(idx + 1, animal))

1: cat
2: dog
3: monkey


In [28]:
# Dictionaries

In [29]:
d = {'cat': 'cute', 'dog': 'furry'}
print(d['cat'])

cute


In [30]:
d['fish'] = 'wet'
print(d['fish'])

wet


In [31]:
del d['fish']

In [32]:
# Loop

In [33]:
d = {'person': 2, 'cat' : 4, 'spider': 8}
for animal, legs in d.items():
    print('{}: {}'.format(animal, legs))

person: 2
cat: 4
spider: 8


In [34]:
# Function

In [35]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


# Numpy

In [37]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))

<class 'numpy.ndarray'>


In [38]:
print(a.shape)

(3,)


In [39]:
print(a[0], a[1], a[2])

1 2 3


In [40]:
a[0] = 5
print(a)

[5 2 3]


In [41]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [42]:
# create default array

In [43]:
import numpy as np

a = np.zeros((2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [45]:
b = np.ones((1, 2))
print(b)

[[1. 1.]]


In [46]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [47]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [48]:
e = np.random.random((2, 2))
print(e)

[[0.68299843 0.34156741]
 [0.55721739 0.37848683]]


In [49]:
# Array indexing

In [50]:
import numpy as np

In [51]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1:3]

In [52]:
print(a[0, 1])

2


In [53]:
a[0, 1] = 77
print(a[0, 1])

77


In [54]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

row_r1 = a[1, :]
row_r2 = a[1: 2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [55]:
# caculate on a array

In [56]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [58]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [60]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [61]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [62]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [63]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [64]:
# use to multiple element-wise but not multip matrix normal. 
# instead of use np.dot to multip matrix.

In [65]:
import numpy as np

In [66]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [68]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [69]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [70]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis=0)) # row
print(np.sum(x, axis=1)) # column

10
[4 6]
[3 7]


In [71]:
# Broadcasting
# is a technique to accept numpy work with arrays have different shape
# to handle calculate

In [74]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # create 1 array has same directions

In [76]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [77]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
